Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pold/Dropbox/Uni/Radboud/Music_Cognition/nPVI/experiment.py", line 8, in <module>
    songs = listdir(base_path)
OSError: [Errno 2] No such file or directory: '/home/pold/Documents/Uni/Radboud/Music_Cognition/nPVI/songs'
>>> 